/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MailchimpPopup {
    'headline': string;
    'onCloseClick': () => void;
    'onSubscribe': ({ email }) => void;
    'subheadline': string;
    'visible': boolean;
  }
}

declare global {


  interface HTMLMailchimpPopupElement extends Components.MailchimpPopup, HTMLStencilElement {}
  var HTMLMailchimpPopupElement: {
    prototype: HTMLMailchimpPopupElement;
    new (): HTMLMailchimpPopupElement;
  };
  interface HTMLElementTagNameMap {
    'mailchimp-popup': HTMLMailchimpPopupElement;
  }
}

declare namespace LocalJSX {
  interface MailchimpPopup extends JSXBase.HTMLAttributes<HTMLMailchimpPopupElement> {
    'headline'?: string;
    'onCloseClick'?: () => void;
    'onSubscribe'?: ({ email }) => void;
    'subheadline'?: string;
    'visible'?: boolean;
  }

  interface IntrinsicElements {
    'mailchimp-popup': MailchimpPopup;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


